default_twitter: &default_twitter
  twitter_api_key: '3FKXyE1DnR0hLIeQNCCPSgzh5'
  twitter_api_secret: ' RiqcRplrIKNRTZHA0H5TzRGYQK7ESAH5LgQniCykCzRWwATuYT'

development:
  secret_key_base: da119feb9c24f88b3ccfe8c22b03eb1484d084281a34734bbea873ee21667df652efc9b1dceacfd4e5fe15c04b3e1a838cac83485cf9213fd34abb63aff8e1d5
  <<: *default_twitter

test:
  secret_key_base: 0252a0ef8d5dd98f73af5866f020b5935607eb60c573275431e6d4b766cc16c45e6fcfe57d8ddac244ca3b5a5fb1cee1cdfbe4dfa48f61c1abbbc5dcf9aa5af0
  <<: *default_twitter

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
