# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da119feb9c24f88b3ccfe8c22b03eb1484d084281a34734bbea873ee21667df652efc9b1dceacfd4e5fe15c04b3e1a838cac83485cf9213fd34abb63aff8e1d5

test:
  secret_key_base: 0252a0ef8d5dd98f73af5866f020b5935607eb60c573275431e6d4b766cc16c45e6fcfe57d8ddac244ca3b5a5fb1cee1cdfbe4dfa48f61c1abbbc5dcf9aa5af0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
